### ISSUE TITLE
Problems with mlogit estimation

### ISSUE THREAD

**Issue by spittssj** [conda-forge/r-mlogit-feedstock#16]
I'm trying to use <code>mlogit</code> to estimate a simple model and running into problems. I get coefficient values of 0 for the model below using [CPS March 2009 data](https://www.ssc.wisc.edu/~bhansen/econometrics/cps09mar.dta) to estimate a logit on marital status as a function of age. Does anyone have any idea how to troubleshoot? 

- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
<pre>
<code>
cps09mar <- read_dta("cps09mar.dta")
cps_women <- cps09mar %>% 
  filter(female == 1) %>% 
  select(age, marital)  
cps_women_id <- cps_women %>% 
  rowid_to_column("ID") %>%
  dummy_cols(select_columns="marital")
cps_women_long <- cps_women_id %>% 
  pivot_longer(cols=starts_with("marital_"), 
               names_to="choice", values_to="chosen") %>%
  mutate(choice=as.numeric(str_sub(choice, 
                            str_length(choice), 
                            str_length(choice))))
cps_df <- cps_women_long %>% data.frame %>%
  dfidx(choice="chosen", 
        idx="ID",
        idnames=c("ID","choice"))
mlogit(marital ~ 0 | age , cps_df)

Call:
mlogit(formula = marital ~ 0 | age, data = H, method = "nr")

Coefficients:
(Intercept):2  (Intercept):3  (Intercept):4  (Intercept):5  (Intercept):6  
            0              0              0              0              0  
(Intercept):7          age:2          age:3          age:4          age:5  
            0              0              0              0              0  
        age:6          age:7  
            0              0  
</code>
</pre>

</code>
</pre>

The data frame <code>cps_df</code> looks like this:
<code><pre>
 first 10 observations out of 151214 
   age marital chosen idx
1   41       1   TRUE 1:1
2   41       1  FALSE 1:2
3   41       1  FALSE 1:3
4   41       1  FALSE 1:4
5   41       1  FALSE 1:5
6   41       1  FALSE 1:6
7   41       1  FALSE 1:7
8   66       5  FALSE 2:1
9   66       5  FALSE 2:2
10  66       5  FALSE 2:3

indexes
 ID choice
1   1      1
2   1      2
3   1      3
4   1      4
5   1      5
6   1      6
7   1      7
8   2      1
9   2      2
10  2      3
indexes:  1, 2 

</pre>
</code>

<br/>
Environment (<code>conda list</code>):
<details>
# Name                    Version                   Build  Channel
_r-mutex                  1.0.1               anacondar_1    conda-forge
bwidget                   1.9.14               h694c41f_0    conda-forge
bzip2                     1.0.8                hc929b4f_4    conda-forge
c-ares                    1.17.1               hc929b4f_0    conda-forge
ca-certificates           2021.1.19            hecd8cb5_0  
cairo                     1.16.0            h4ec454a_1007    conda-forge
cctools_osx-64            949.0.1             h2f0f38f_19    conda-forge
clang                     11.0.1               h694c41f_1    conda-forge
clang-11                  11.0.1          default_hf8bb9ca_1    conda-forge
clang_osx-64              11.0.1               hb91bd55_0    conda-forge
clangxx                   11.0.1          default_hf8bb9ca_1    conda-forge
clangxx_osx-64            11.0.1               h7e1b574_0    conda-forge
compiler-rt               11.0.1               h654b07c_0    conda-forge
compiler-rt_osx-64        11.0.1               h8c5fa43_0    conda-forge
curl                      7.71.1               hcb81553_8    conda-forge
fontconfig                2.13.1            hd23ceaa_1004    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
fribidi                   1.0.10               hbcb3906_0    conda-forge
gettext                   0.19.8.1          h7937167_1005    conda-forge
gfortran_impl_osx-64      9.3.0               h8668ab3_17    conda-forge
gfortran_osx-64           9.3.0               h0d18d9c_12    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
graphite2                 1.3.13            h2e338ed_1001    conda-forge
gsl                       2.6                  h71c5fe9_2    conda-forge
harfbuzz                  2.7.4                hf28d55f_0    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
isl                       0.22.1               hb1e8313_2    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
ld64_osx-64               530                 hea264c1_19    conda-forge
ldid                      2.1.2                h7660a38_2    conda-forge
libblas                   3.9.0                7_openblas    conda-forge
libcblas                  3.9.0                7_openblas    conda-forge
libclang-cpp11            11.0.1          default_hf8bb9ca_1    conda-forge
libcurl                   7.71.1               h9bf37e3_8    conda-forge
libcxx                    11.0.1               habf9029_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_17    conda-forge
libgfortran-devel_osx-64  9.3.0               h6c81a4c_17    conda-forge
libgfortran5              9.3.0               h6c81a4c_17    conda-forge
libglib                   2.66.4               h7424822_2    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0                7_openblas    conda-forge
libllvm11                 11.0.1               h223d4b2_0    conda-forge
libnghttp2                1.41.0               h7580e61_2    conda-forge
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libssh2                   1.9.0                h8a08a2b_5    conda-forge
libtiff                   4.2.0                h355d032_0    conda-forge
libwebp-base              1.1.0                hbcb3906_3    conda-forge
libxml2                   2.9.10               h802ca4f_3    conda-forge
llvm-openmp               11.0.1               h7c73e74_0    conda-forge
llvm-tools                11.0.1               h223d4b2_0    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
make                      4.3                  h22f3db7_1    conda-forge
mpc                       1.1.0             ha57cd0f_1009    conda-forge
mpfr                      4.0.2                h72d8aaf_1    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
openssl                   1.1.1i               h35c211d_0    conda-forge
pandoc                    2.11.4               h35c211d_0    conda-forge
pango                     1.42.4               ha86e081_5    conda-forge
pcre                      8.44                 hb1e8313_0    conda-forge
pcre2                     10.36                h91abf9c_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
r-abind                   1.4_5           r40h6115d3f_1003    conda-forge
r-aer                     1.2_9                     r40_1    conda-forge
r-askpass                 1.1               r40h17f1fa6_2    conda-forge
r-assertthat              0.2.1             r40h6115d3f_2    conda-forge
r-backports               1.2.1             r40h066c5db_0    conda-forge
r-base                    4.0.3                h2b2b636_4    conda-forge
r-base64enc               0.1_3           r40h17f1fa6_1004    conda-forge
r-bdsmatrix               1.3_4             r40h17f1fa6_1    conda-forge
r-blob                    1.2.1             r40h6115d3f_1    conda-forge
r-boot                    1.3_26            r40hc72bb7e_0    conda-forge
r-brio                    1.1.1             r40h066c5db_0    conda-forge
r-broom                   0.7.3             r40hc72bb7e_0    conda-forge
r-callr                   3.5.1             r40h142f84f_0    conda-forge
r-car                     3.0_10            r40h6115d3f_0    conda-forge
r-cardata                 3.0_4             r40h6115d3f_0    conda-forge
r-cellranger              1.1.0           r40h6115d3f_1003    conda-forge
r-cli                     2.2.0             r40hc72bb7e_0    conda-forge
r-clipr                   0.7.1             r40h142f84f_0    conda-forge
r-colorspace              2.0_0             r40h6b199c2_0    conda-forge
r-conquer                 1.0.2             r40h3e9696b_1    conda-forge
r-cpp11                   0.2.5             r40hc72bb7e_0    conda-forge
r-crayon                  1.3.4           r40h6115d3f_1003    conda-forge
r-curl                    4.3               r40h17f1fa6_1    conda-forge
r-data.table              1.13.6            r40h066c5db_0    conda-forge
r-dbi                     1.1.1             r40hc72bb7e_0    conda-forge
r-dbplyr                  2.0.0             r40hc72bb7e_0    conda-forge
r-desc                    1.2.0           r40h6115d3f_1003    conda-forge
r-dfidx                   0.0_4             r40hc72bb7e_0    conda-forge
r-diffobj                 0.3.3             r40h066c5db_0    conda-forge
r-digest                  0.6.27            r40h342fd00_0    conda-forge
r-dplyr                   1.0.3             r40h815b84a_0    conda-forge
r-ellipsis                0.3.1             r40h17f1fa6_0    conda-forge
r-evaluate                0.14              r40h6115d3f_2    conda-forge
r-fansi                   0.4.2             r40h066c5db_0    conda-forge
r-farver                  2.0.3             r40hc5da6b9_1    conda-forge
r-forcats                 0.5.0             r40h6115d3f_1    conda-forge
r-foreign                 0.8_81            r40h066c5db_0    conda-forge
r-formula                 1.2_4             r40h142f84f_0    conda-forge
r-fs                      1.5.0             r40h710217c_0    conda-forge
r-gbrd                    0.4_11          r40h6115d3f_1002    conda-forge
r-generics                0.1.0             r40hc72bb7e_0    conda-forge
r-ggplot2                 3.3.3             r40hc72bb7e_0    conda-forge
r-glue                    1.4.2             r40h066c5db_0    conda-forge
r-gtable                  0.3.0             r40h6115d3f_3    conda-forge
r-haven                   2.3.1             r40hee97c7f_0    conda-forge
r-highr                   0.8               r40h6115d3f_2    conda-forge
r-hms                     1.0.0             r40hc72bb7e_0    conda-forge
r-htmltools               0.5.1.1           r40h815b84a_0    conda-forge
r-httr                    1.4.2             r40h6115d3f_0    conda-forge
r-isoband                 0.2.3             r40h1019320_0    conda-forge
r-jsonlite                1.7.2             r40h066c5db_0    conda-forge
r-knitr                   1.30              r40h6115d3f_0    conda-forge
r-labeling                0.4.2             r40h142f84f_0    conda-forge
r-lattice                 0.20_41           r40h066c5db_3    conda-forge
r-lifecycle               0.2.0             r40h6115d3f_1    conda-forge
r-lme4                    1.1_26            r40h1019320_0    conda-forge
r-lmtest                  0.9_38            r40h43cf36c_1    conda-forge
r-lubridate               1.7.9.2           r40h1019320_0    conda-forge
r-magrittr                2.0.1             r40h066c5db_1    conda-forge
r-maptools                1.0_2             r40h800e0f2_0    conda-forge
r-markdown                1.1               r40h066c5db_1    conda-forge
r-mass                    7.3_53            r40h066c5db_0    conda-forge
r-matrix                  1.3_2             r40he51b063_0    conda-forge
r-matrixmodels            0.4_1           r40h6115d3f_1003    conda-forge
r-matrixstats             0.57.0            r40h066c5db_0    conda-forge
r-maxlik                  1.4_6             r40hc72bb7e_0    conda-forge
r-mgcv                    1.8_33            r40hb6d66fe_0    conda-forge
r-mime                    0.9               r40h066c5db_1    conda-forge
r-minqa                   1.2.4           r40ha6353f9_1006    conda-forge
r-misctools               0.6_26            r40h6115d3f_1    conda-forge
r-mlogit                  1.1_1             r40h142f84f_0    conda-forge
r-modelr                  0.1.8             r40h6115d3f_0    conda-forge
r-munsell                 0.5.0           r40h6115d3f_1003    conda-forge
r-nlme                    3.1_151           r40h1a6e9bf_0    conda-forge
r-nloptr                  1.2.2.2           r40hc5da6b9_0    conda-forge
r-nnet                    7.3_15            r40h066c5db_0    conda-forge
r-numderiv                2016.8_1.1        r40h6115d3f_3    conda-forge
r-openssl                 1.4.3             r40ha713f70_0    conda-forge
r-openxlsx                4.2.3             r40h342fd00_0    conda-forge
r-pbkrtest                0.5_0.1           r40hc72bb7e_0    conda-forge
r-pillar                  1.4.7             r40hc72bb7e_0    conda-forge
r-pkgbuild                1.2.0             r40hc72bb7e_0    conda-forge
r-pkgconfig               2.0.3             r40h6115d3f_1    conda-forge
r-pkgload                 1.1.0             r40hc5da6b9_0    conda-forge
r-plm                     2.4_0             r40hc72bb7e_0    conda-forge
r-plyr                    1.8.6             r40hc5da6b9_1    conda-forge
r-praise                  1.0.0           r40h6115d3f_1004    conda-forge
r-prettyunits             1.1.1             r40h6115d3f_1    conda-forge
r-processx                3.4.5             r40he27d7ee_0    conda-forge
r-progress                1.2.2             r40h6115d3f_2    conda-forge
r-ps                      1.5.0             r40h066c5db_0    conda-forge
r-purrr                   0.3.4             r40h17f1fa6_1    conda-forge
r-quantreg                5.83              r40h2704daa_0    conda-forge
r-r6                      2.5.0             r40hc72bb7e_0    conda-forge
r-rbibutils               2.0               r40he27d7ee_0    conda-forge
r-rcolorbrewer            1.1_2           r40h6115d3f_1003    conda-forge
r-rcpp                    1.0.6             r40h815b84a_0    conda-forge
r-rcpparmadillo           0.10.1.2.2        r40hbe96a68_0    conda-forge
r-rcppeigen               0.3.3.9.1         r40hbe96a68_0    conda-forge
r-rdpack                  2.1               r40hc72bb7e_0    conda-forge
r-readr                   1.4.0             r40h342fd00_0    conda-forge
r-readxl                  1.3.1             r40hee97c7f_4    conda-forge
r-rematch                 1.0.1           r40h6115d3f_1003    conda-forge
r-rematch2                2.1.2             r40h6115d3f_1    conda-forge
r-reprex                  0.3.0             r40h6115d3f_2    conda-forge
r-reshape2                1.4.4             r40hc5da6b9_1    conda-forge
r-rio                     0.5.16          r40h6115d3f_1002    conda-forge
r-rlang                   0.4.10            r40h066c5db_0    conda-forge
r-rmarkdown               2.6               r40hc72bb7e_0    conda-forge
r-rprojroot               2.0.2             r40hc72bb7e_0    conda-forge
r-rstudioapi              0.13              r40hc72bb7e_0    conda-forge
r-rvest                   0.3.6             r40h6115d3f_0    conda-forge
r-sandwich                3.0_0             r40h142f84f_0    conda-forge
r-scales                  1.1.1             r40h6115d3f_0    conda-forge
r-selectr                 0.4_2             r40h6115d3f_1    conda-forge
r-sp                      1.4_5             r40h066c5db_0    conda-forge
r-sparsem                 1.78              r40h43cf36c_2    conda-forge
r-spatial                 7.3_13            r40h066c5db_0    conda-forge
r-stargazer               5.2.2             r40h6115d3f_2    conda-forge
r-statmod                 1.4.35            r40h508aa58_1    conda-forge
r-stringi                 1.5.3             r40h9aeca8d_1    conda-forge
r-stringr                 1.4.0             r40h6115d3f_2    conda-forge
r-survival                3.2_7             r40h800e0f2_0    conda-forge
r-sys                     3.4               r40h800e0f2_0    conda-forge
r-testthat                3.0.1             r40h815b84a_0    conda-forge
r-tibble                  3.0.5             r40h066c5db_0    conda-forge
r-tidyr                   1.1.2             r40h710217c_0    conda-forge
r-tidyselect              1.1.0             r40h6115d3f_0    conda-forge
r-tidyverse               1.3.0             r40h6115d3f_2    conda-forge
r-tinytex                 0.29              r40hc72bb7e_0    conda-forge
r-utf8                    1.1.4           r40h17f1fa6_1003    conda-forge
r-vctrs                   0.3.6             r40h066c5db_0    conda-forge
r-viridislite             0.3.0           r40h6115d3f_1003    conda-forge
r-waldo                   0.2.3             r40hc72bb7e_0    conda-forge
r-whisker                 0.4               r40h6115d3f_1    conda-forge
r-withr                   2.4.1             r40hc72bb7e_0    conda-forge
r-xfun                    0.20              r40h066c5db_0    conda-forge
r-xml2                    1.3.2             r40hc5da6b9_1    conda-forge
r-yaml                    2.2.1             r40h066c5db_1    conda-forge
r-zeallot                 0.1.0           r40h6115d3f_1002    conda-forge
r-zip                     2.1.1             r40h800e0f2_0    conda-forge
r-zoo                     1.8_8             r40h17f1fa6_0    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
tapi                      1100.0.11            h9ce4665_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
tktable                   2.10                 h49f0cf7_3    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.8                hf387650_1    conda-forge
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>
    active environment : apec8213
    active env location : /Users/stephenpitts/miniconda3/envs/apec8213
            shell level : 1
       user config file : /Users/stephenpitts/.condarc
 populated config files : /Users/stephenpitts/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/stephenpitts/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/stephenpitts/miniconda3/pkgs
                          /Users/stephenpitts/.conda/pkgs
       envs directories : /Users/stephenpitts/miniconda3/envs
                          /Users/stephenpitts/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Darwin/20.3.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
</details>

**Comment by nsoranzo** [comment]
This seems a problem with mlogit itself more than an issue with the conda package for it. I'd suggest you report your issue to the mlogit author indicated on https://cran.r-project.org/web/packages/mlogit/index.html

**Comment by spittssj** [comment]
The code works fine on a colleague's Windows PC with `mlogit` installed through RStudio, so it probably has something to do with MacOS X as well.

I tried two other R new environments.

### A fresh one with only r-mlogit installed from conda ###
<pre><code>
stephenpitts@Ellacuria ~ % mamba create -n r-mlogittest r-base r-mlogit
</code></pre>

### An even fresher one with mlogit installed via CRAN ###
<pre><code>
stephenpitts@Ellacuria ~ % mamba create -n r-mlogittest2 r-base
</code></pre>

These were the packages I installed from source there:
<pre><code>
library(tidyverse)
library(nnet)
library(haven)
library(mlogit)
library(fastDummies)
</code></pre>

I had the same problem of zero coefficients in both environments. I reached out to Yves Croissant and am waiting to hear back.

It's funny -- I was hopeful that switching to Conda would fix some of these complex issues involving R libraries with underlying C dependencies. Instead, this is the second time in two weeks I've run into an issue like this. Last week I was debugging a GIS toolchain.

Do you know what C libraries `mlogit` depends on? Could it be possible that something outside of conda (in my homebrew installation?) is affecting things?

Thanks.
